### PR TITLE
AppStudio. Workspace-Controller-Compute Layout diagram

### PR DESCRIPTION
**Pull request by alexeykazakov**

### CODE REVIEW

**Comment by amfred** [comment]
We'll also have an App Studio Ops BYO cluster.  So far it just has Grafana on it; it will probably have Thanos later, and it will probably end up with other services like the QE dashboard as well.  At the moment these things are on the App Studio KCP cluster with everything else, and the ops tools can stay there indefinitely until there's a reason to move them. For Service Preview, I want to have a new App Studio Control Plane production cluster, for several reasons.

**Comment by alexeykazakov** [comment]
@amfred this diagram is focusing on the Workspace - Controller - Compute relations. The ops tools is a bit different story. I think we will need a different diagram for that. I would like to avoid adding everything in a single diagram because it may become unreadable. But we can always add the Ops tools later to this diagram if we really want.

**Comment by gorkem** [comment]
The `manages` labeled link from ArgoCD controller goes to only prod environment which creates the impression that only prod is managed by GitOps. Can we add links that extent to other environments as well?

**Comment by alexeykazakov** [comment]
> Can we add links that extent to other environments as well?

Added.

**Review by amfred — APPROVED** [review]

**Comment by alexeykazakov** [comment]
@amfred let's have a conversation about our Ops stack. I think it's clear what we want to do now but let's talk about what we want to do for SP. And we will either add it to this diagram (as a new PR) or create a new diagram for that.

**Pull request merged**
