### PR TITLE
Add integration service architecture diagram

### PR DESCRIPTION
**Pull request by sonam1412**
Integration service architecture diagram

### CODE REVIEW

**Comment by dirgim** [comment]
Should this replace the existing diagram at https://github.com/redhat-appstudio/book/blob/main/diagrams/hacbs-data-flow.jpg ?

**Comment by sonam1412** [comment]
> Should this replace the existing diagram at https://github.com/redhat-appstudio/book/blob/main/diagrams/hacbs-data-flow.jpg ?

I guess it should.
Replaced

**Review by arewm — APPROVED** [review]
Is there any change to the content of the diagram or just the naming of it?

**Comment by sonam1412** [comment]
> Is there any change to the content of the diagram or just the naming of it?

This is just a basic structure which is still the same. We can improve it in future, if needed

**Review by dirgim — APPROVED** [review]
LGTM

**Pull request merged**
