### PR TITLE
Add HAS API doc

### PR DESCRIPTION
**Pull request by kim-tsao**
Move HAS API docs from google docs to the book of AppStudio

https://issues.redhat.com/browse/DEVHAS-479

### CODE REVIEW

**Review by maysunfaisal — APPROVED** [review]

**Review by johnmcollier — APPROVED** [review]

**Comment by ralphbean** [comment]
How will someone navigate to the new docs in `book/HAS/`? Should there be links added there from `book/hybrid-application-service.md`?

**Comment by maysunfaisal** [comment]
> How will someone navigate to the new docs in `book/HAS/`? Should there be links added there from `book/hybrid-application-service.md`?

@ralphbean there will be a follow up PR to add the links. But we can add a temp link with this PR until the next PR
cc @kim-tsao

**Comment by kim-tsao** [comment]
> > How will someone navigate to the new docs in `book/HAS/`? Should there be links added there from `book/hybrid-application-service.md`?
> 
> @ralphbean there will be a follow up PR to add the links. But we can add a temp link with this PR until the next PR cc @kim-tsao

@ralphbean we are migrating our docs in stages.  We plan to add a link to this doc in the main HAS design doc which is empty right now but the next step after merging is to add a link to the application-api docs which are generated

**Comment by ralphbean** [comment]
That's all good! No objection from me since you guys have a plan. :+1: to merge.

**Review by ralphbean — APPROVED** [review]

**Pull request merged**
