### PR TITLE
chore(RHTAPREL-260): remove references to releasestrategy

### PR DESCRIPTION
**Pull request by scoheb**
- update release-service workflow
- update release standing attribution
- update roles and permissions

### CODE REVIEW

**Comment by arewm** [comment]
https://github.com/redhat-appstudio/book/blob/main/diagrams/release-service/hacbs-release-service-data-flow.jpg has a reference to the release strategy as well

**Comment by scoheb** [comment]
> https://github.com/redhat-appstudio/book/blob/main/diagrams/release-service/hacbs-release-service-data-flow.jpg has a reference to the release strategy as well

Nice catch! Fixed

**Review by arewm — APPROVED** [review]

**Review by johnbieren — APPROVED** [review]
LGTM, not sure if you want to add any references to ReleaseServiceConfigs in the lists of CRDs we touch, but it probably isn't in scope of the ReleaseStrategy change anyways

**Comment by scoheb** [comment]
> LGTM, not sure if you want to add any references to ReleaseServiceConfigs in the lists of CRDs we touch, but it probably isn't in scope of the ReleaseStrategy change anyways

Yes. I'd rather leave that to another PR.

**Pull request merged**
