### PR TITLE
StoneSoup workspace layout in post-KCP environment

### PR DESCRIPTION
**Pull request by alexeykazakov**

### CODE REVIEW

**Comment by sbose78** [comment]
Would you be able to add some textual commentary which interprets the diagram, please?

**Review by ralphbean — APPROVED** [review]
Some text to describe this would be nice - but, it feels like we need an ADR titled "no more kcp", and this is the diagram that supports that ADR.

It's okay with me if we submit that separately.

**Comment by alexeykazakov** [comment]
Yeah.. this PR is just to replace the outdate diagram. We sill need a proper ADR which I would do in a separate PR.

**Review by MatousJobanek — APPROVED** [review]
:+1: for phase 2
do we want to mention somewhere also the plan for SP (summit) - aka phase 1 or 1.5?

**Comment by MatousJobanek** [comment]
> This looks good, but I think it's missing the Sandbox Host and Member Operators?

This is abstracted by the host & member clusters. We need to hide some of the details, otherwise, it would be hard to understand the diagram.

**Comment by amfred** [comment]
> > This looks good, but I think it's missing the Sandbox Host and Member Operators?
> 
> This is abstracted by the host & member clusters. We need to hide some of the details, otherwise, it would be hard to understand the diagram.

Those operators are not any less important than the other operators in the diagram. In fact, they're quite important and they come up in conversations often.

**Pull request merged**
