### PR TITLE
[DEVHAS-297]add cdq detection and validation logic

### PR DESCRIPTION
**Pull request by yangcao77**
For https://issues.redhat.com/browse/DEVHAS-297

Adding cdq detection and validation logic doc

### CODE REVIEW

**Review by arewm — APPROVED** [review]
Thanks!

**Review by amfred — APPROVED** [review]

**Comment by amfred** [comment]
@elsony This looks good to me; do you concur?

**Review by elsony — APPROVED** [review]
/lgtm

**Comment by yangcao77** [comment]
@amfred @arewm May I get this PR merged? Thx!

**Pull request merged**
